BesselBasis_trainable: false
PolynomialCutoff_p: 6
_jit_bailout_depth: 2
_jit_fuser: fuser1
_jit_fusion_strategy:
- !!python/tuple
  - DYNAMIC
  - 3
allow_tf32: true
append: true
ase_args:
  format: extxyz
avg_num_neighbors: 31.514259338378906
batch_size: 100
code_commits:
  allegro: 87a169c973c891b54bfba8729b393f862dc1d6e7
  e3nn: 19a89aae08f44a0a95600d6e37d398fdbf626336
  nequip: 3f03c7766b70f21bc9894d00db01c8e8909b90f6
dataloader_num_workers: 0
dataset: ase
dataset_AtomicData_options:
  r_max: 6.0
dataset_file_name: ../datasets/WSe2_Split_intra_train.extxyz
dataset_seed: 123456
dataset_statistics_stride: 1
default_dtype: float32
device: cuda
e3nn_version: 0.5.1
early_stopping: null
early_stopping_kwargs: null
early_stopping_lower_bounds:
  LR: 1.0e-05
edge_eng_mlp_initialization: uniform
edge_eng_mlp_latent_dimensions:
- 128
edge_eng_mlp_nonlinearity: null
ema_decay: 0.99
ema_use_num_updates: true
embed_initial_edge: true
end_of_batch_callbacks: []
end_of_epoch_callbacks: []
end_of_train_callbacks: []
env_embed_mlp_initialization: uniform
env_embed_mlp_latent_dimensions: []
env_embed_mlp_nonlinearity: null
env_embed_multiplicity: 8
equivariance_test: false
exclude_keys: []
final_callbacks: []
gpu_oom_offload: false
grad_anomaly_mode: false
include_keys:
- atom_types
init_callbacks: []
irreps_edge_sh: 1x0e+1x1o+1x2e+1x3o
l_max: 3
latent_mlp_initialization: uniform
latent_mlp_latent_dimensions:
- 128
latent_mlp_nonlinearity: silu
latent_resnet: true
learning_rate: 0.001
log_batch_freq: 500
log_epoch_freq: 1
loss_coeffs:
  forces:
  - 1.0
  total_energy:
  - 1.0
lr_scheduler_factor: 0.8
lr_scheduler_kwargs:
  cooldown: 0
  eps: 1.0e-08
  factor: 0.8
  min_lr: 0
  mode: min
  patience: 10
  threshold: 0.0001
  threshold_mode: rel
  verbose: false
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 10
max_epochs: 2000
max_gradient_norm: .inf
metrics_components:
- - forces
  - mae
- - forces
  - rmse
- - total_energy
  - rmse
- - total_energy
  - rmse
  - PerAtom: true
metrics_key: validation_loss
model_builders:
- allegro.model.Allegro
- PerSpeciesRescale
- ForceOutput
- RescaleEnergyEtc
model_debug_mode: false
model_dtype: float32
n_train: 400
n_train_per_epoch: null
n_val: 100
nequip_version: 0.6.0
nonscalars_include_parity: true
num_layers: 3
num_types: 6
optimizer_amsgrad: false
optimizer_betas: &id001 !!python/tuple
- 0.9
- 0.999
optimizer_eps: 1.0e-08
optimizer_kwargs:
  amsgrad: false
  betas: *id001
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: null
  maximize: false
  weight_decay: 0
optimizer_name: Adam
optimizer_weight_decay: 0
parity: o3_full
r_max: 6.0
report_init_validation: true
root: WSe2_MoS2
run_id: uwdsYvErdB2JC-5F5KHa8bKp-E1K0zu1hhr0ctZ_moc
run_name: Wse2model_v1
save_checkpoint_freq: -1
save_ema_checkpoint_freq: -1
seed: 123456
shuffle: true
tensorboard: false
torch_version: !!python/object/new:torch.torch_version.TorchVersion
- 2.1.0
train_idcs: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
    ZQpxAVgOAAAAOTQyMDAxMzgwMTk2MDBxAlgDAAAAY3B1cQNN9AFOdHEEUS6AAl1xAFgOAAAAOTQy
    MDAxMzgwMTk2MDBxAWEu9AEAAAAAAAAJAQAAAAAAAB4AAAAAAAAAFAEAAAAAAAAlAAAAAAAAAOwB
    AAAAAAAALgEAAAAAAACNAQAAAAAAAN8AAAAAAAAA5wAAAAAAAABkAAAAAAAAADEAAAAAAAAAogAA
    AAAAAABMAQAAAAAAAI8BAAAAAAAAAgAAAAAAAADHAQAAAAAAACsAAAAAAAAAvAEAAAAAAAB5AQAA
    AAAAAJkBAAAAAAAAxgEAAAAAAADwAAAAAAAAAEQAAAAAAAAANgEAAAAAAADqAAAAAAAAAEcAAAAA
    AAAARgEAAAAAAAA8AQAAAAAAABoAAAAAAAAAmQAAAAAAAAAbAAAAAAAAAMkAAAAAAAAA5QEAAAAA
    AAAPAAAAAAAAAO8BAAAAAAAAnwEAAAAAAADIAQAAAAAAANcBAAAAAAAA1QEAAAAAAAC8AAAAAAAA
    AAAAAAAAAAAA2gEAAAAAAAApAQAAAAAAAMEAAAAAAAAAnwAAAAAAAABmAAAAAAAAADMAAAAAAAAA
    kwAAAAAAAACwAAAAAAAAAIwBAAAAAAAAtgAAAAAAAAAAAQAAAAAAAEMBAAAAAAAAfQEAAAAAAACE
    AQAAAAAAAGMAAAAAAAAAOAAAAAAAAABXAQAAAAAAACYAAAAAAAAAvwAAAAAAAADCAQAAAAAAAOgB
    AAAAAAAAPQAAAAAAAAAnAAAAAAAAAMQAAAAAAAAAfwEAAAAAAABnAQAAAAAAACUBAAAAAAAA8gEA
    AAAAAACAAAAAAAAAAHkAAAAAAAAAeAAAAAAAAACXAQAAAAAAADoBAAAAAAAArAEAAAAAAAB3AQAA
    AAAAAJ4AAAAAAAAAugAAAAAAAABZAAAAAAAAAGkBAAAAAAAAJgEAAAAAAAAXAQAAAAAAAJEBAAAA
    AAAA0QEAAAAAAAAqAAAAAAAAAHUBAAAAAAAA8QAAAAAAAAA+AQAAAAAAAPoAAAAAAAAA7gAAAAAA
    AADaAAAAAAAAAHEAAAAAAAAA6gEAAAAAAACMAAAAAAAAAO4BAAAAAAAAHgEAAAAAAAA6AAAAAAAA
    ACcBAAAAAAAAGAEAAAAAAADAAAAAAAAAANQAAAAAAAAAvgAAAAAAAAD1AAAAAAAAADUBAAAAAAAA
    kAEAAAAAAADMAQAAAAAAAJYBAAAAAAAASQAAAAAAAADpAQAAAAAAACEAAAAAAAAAhQEAAAAAAACH
    AQAAAAAAAKsAAAAAAAAAsAEAAAAAAADzAQAAAAAAANkBAAAAAAAAIAEAAAAAAABHAQAAAAAAAHYB
    AAAAAAAAcgEAAAAAAAD8AAAAAAAAAGMBAAAAAAAAiQAAAAAAAABXAAAAAAAAAGEAAAAAAAAA8gAA
    AAAAAADtAAAAAAAAAMMBAAAAAAAAoAAAAAAAAAA3AQAAAAAAAHcAAAAAAAAACwAAAAAAAADOAQAA
    AAAAABYAAAAAAAAAGwEAAAAAAACJAQAAAAAAAAYBAAAAAAAAaAAAAAAAAAD7AAAAAAAAAC8AAAAA
    AAAA5gEAAAAAAAA/AQAAAAAAAO8AAAAAAAAArwEAAAAAAADkAAAAAAAAAJwAAAAAAAAAMQEAAAAA
    AADAAQAAAAAAAHYAAAAAAAAA1gAAAAAAAACNAAAAAAAAAGsBAAAAAAAA8wAAAAAAAAAHAQAAAAAA
    AGoAAAAAAAAAtQAAAAAAAACLAAAAAAAAANwAAAAAAAAAuwAAAAAAAADRAAAAAAAAAOIAAAAAAAAA
    OAEAAAAAAABfAAAAAAAAAF4AAAAAAAAAWwAAAAAAAADKAQAAAAAAAHABAAAAAAAAbAAAAAAAAACp
    AQAAAAAAAMoAAAAAAAAANgAAAAAAAAABAAAAAAAAAJEAAAAAAAAAcwEAAAAAAADLAQAAAAAAAEoB
    AAAAAAAAqgAAAAAAAABfAQAAAAAAADcAAAAAAAAAeAEAAAAAAACvAAAAAAAAABAAAAAAAAAAAgEA
    AAAAAAC7AQAAAAAAAMcAAAAAAAAAOQAAAAAAAACWAAAAAAAAAHoAAAAAAAAAhwAAAAAAAACmAQAA
    AAAAAA0BAAAAAAAA0wAAAAAAAACbAAAAAAAAANAAAAAAAAAApgAAAAAAAADMAAAAAAAAADsAAAAA
    AAAABQAAAAAAAADjAAAAAAAAAHsBAAAAAAAAsQEAAAAAAACCAAAAAAAAAIIBAAAAAAAA3QAAAAAA
    AAARAQAAAAAAAIgAAAAAAAAA/gAAAAAAAAAIAQAAAAAAAKkAAAAAAAAAQgAAAAAAAAD4AAAAAAAA
    AK4AAAAAAAAA6AAAAAAAAACuAQAAAAAAAOkAAAAAAAAAHwEAAAAAAACaAAAAAAAAAIMAAAAAAAAA
    vgEAAAAAAAAIAAAAAAAAAKUBAAAAAAAAEwAAAAAAAADFAQAAAAAAAFwBAAAAAAAAWwEAAAAAAAAh
    AQAAAAAAAC0AAAAAAAAAuQAAAAAAAABPAQAAAAAAACIAAAAAAAAAsgEAAAAAAAAoAQAAAAAAAJUB
    AAAAAAAAbgEAAAAAAAAZAQAAAAAAACkAAAAAAAAA/wAAAAAAAABnAAAAAAAAAKEBAAAAAAAA1AEA
    AAAAAACeAQAAAAAAAM8AAAAAAAAA4gEAAAAAAABwAAAAAAAAADIBAAAAAAAADwEAAAAAAABmAQAA
    AAAAABUAAAAAAAAAfQAAAAAAAADSAQAAAAAAAOUAAAAAAAAAPQEAAAAAAAA8AAAAAAAAAB0AAAAA
    AAAAqAAAAAAAAACgAQAAAAAAAB8AAAAAAAAAYAEAAAAAAAC4AQAAAAAAABIAAAAAAAAAQwAAAAAA
    AABUAAAAAAAAAG4AAAAAAAAAXgEAAAAAAABLAQAAAAAAACMBAAAAAAAAlAAAAAAAAACEAAAAAAAA
    AEIBAAAAAAAARQAAAAAAAABoAQAAAAAAAE0BAAAAAAAAlwAAAAAAAAC4AAAAAAAAABgAAAAAAAAA
    cwAAAAAAAACDAQAAAAAAAFAAAAAAAAAADAAAAAAAAABgAAAAAAAAAM0AAAAAAAAAWgEAAAAAAACA
    AQAAAAAAACsBAAAAAAAAEgEAAAAAAABpAAAAAAAAAEkBAAAAAAAA/QAAAAAAAADXAAAAAAAAADAA
    AAAAAAAAcgAAAAAAAADQAQAAAAAAAGUAAAAAAAAA3AEAAAAAAAA7AQAAAAAAAMIAAAAAAAAAhgAA
    AAAAAACaAQAAAAAAAGQBAAAAAAAAIAAAAAAAAAAyAAAAAAAAAOsAAAAAAAAAtAAAAAAAAADhAQAA
    AAAAAKEAAAAAAAAAWgAAAAAAAABOAQAAAAAAANsBAAAAAAAAqwEAAAAAAACOAAAAAAAAAKoBAAAA
    AAAApAEAAAAAAABvAAAAAAAAAIUAAAAAAAAA4AAAAAAAAAB7AAAAAAAAAEABAAAAAAAAfgEAAAAA
    AADWAQAAAAAAALcBAAAAAAAAKgEAAAAAAABTAQAAAAAAACQAAAAAAAAASAEAAAAAAAAvAQAAAAAA
    APkAAAAAAAAA2AAAAAAAAABiAAAAAAAAAMkBAAAAAAAAwQEAAAAAAABdAAAAAAAAAE4AAAAAAAAA
    xAEAAAAAAACKAAAAAAAAAH4AAAAAAAAAFQEAAAAAAACTAQAAAAAAAAMBAAAAAAAAvQEAAAAAAAAc
    AAAAAAAAAIoBAAAAAAAA1QAAAAAAAACcAQAAAAAAAIgBAAAAAAAAFAAAAAAAAADNAQAAAAAAAFYA
    AAAAAAAApwEAAAAAAAAtAQAAAAAAAJIAAAAAAAAAQAAAAAAAAAB1AAAAAAAAAOQBAAAAAAAALAAA
    AAAAAACGAQAAAAAAAKIBAAAAAAAAAwAAAAAAAADGAAAAAAAAAFQBAAAAAAAAuQEAAAAAAACVAAAA
    AAAAAE8AAAAAAAAADgAAAAAAAACLAQAAAAAAAJsBAAAAAAAAGQAAAAAAAAA5AQAAAAAAALMBAAAA
    AAAA3wEAAAAAAACYAAAAAAAAADUAAAAAAAAAdAEAAAAAAAA0AAAAAAAAAH8AAAAAAAAAPgAAAAAA
    AACxAAAAAAAAAAEBAAAAAAAAgQAAAAAAAACBAQAAAAAAALMAAAAAAAAADAEAAAAAAACtAAAAAAAA
    AMsAAAAAAAAA9gAAAAAAAAAJAAAAAAAAALUBAAAAAAAAUQEAAAAAAAAcAQAAAAAAAFgAAAAAAAAA
    awAAAAAAAACkAAAAAAAAAAsBAAAAAAAAfAAAAAAAAABYAQAAAAAAAHoBAAAAAAAAQQEAAAAAAAAs
    AQAAAAAAADABAAAAAAAAnQEAAAAAAABVAQAAAAAAAOcBAAAAAAAAyAAAAAAAAADFAAAAAAAAABcA
    AAAAAAAA9wAAAAAAAAC/AQAAAAAAAGEBAAAAAAAASAAAAAAAAABxAQAAAAAAAAoBAAAAAAAARQEA
    AAAAAABTAAAAAAAAAOEAAAAAAAAAtgEAAAAAAADgAQAAAAAAAN0BAAAAAAAAbAEAAAAAAAClAAAA
    AAAAAPEBAAAAAAAA7QEAAAAAAACdAAAAAAAAAKMBAAAAAAAAUAEAAAAAAAC9AAAAAAAAADQBAAAA
    AAAAMwEAAAAAAADTAQAAAAAAABYBAAAAAAAArAAAAAAAAADYAQAAAAAAAKMAAAAAAAAAPwAAAAAA
    AAAEAQAAAAAAAAoAAAAAAAAAjwAAAAAAAABVAAAAAAAAAJAAAAAAAAAAEQAAAAAAAABSAAAAAAAA
    AE0AAAAAAAAABgAAAAAAAACUAQAAAAAAAKgBAAAAAAAAEAEAAAAAAAANAAAAAAAAAOsBAAAAAAAA
    VgEAAAAAAACyAAAAAAAAAHwBAAAAAAAARgAAAAAAAABRAAAAAAAAANsAAAAAAAAAwwAAAAAAAADw
    AQAAAAAAACQBAAAAAAAA3gAAAAAAAADSAAAAAAAAAG0BAAAAAAAAHQEAAAAAAAAFAQAAAAAAAK0B
    AAAAAAAAXQEAAAAAAAAiAQAAAAAAAFIBAAAAAAAAEwEAAAAAAADPAQAAAAAAALoBAAAAAAAA4wEA
    AAAAAAAaAQAAAAAAAG0AAAAAAAAAagEAAAAAAABLAAAAAAAAAKcAAAAAAAAA7AAAAAAAAABiAQAA
    AAAAAEEAAAAAAAAABwAAAAAAAABZAQAAAAAAAFwAAAAAAAAAtAEAAAAAAAAOAQAAAAAAAJIBAAAA
    AAAAbwEAAAAAAAC3AAAAAAAAAPQAAAAAAAAA2QAAAAAAAABMAAAAAAAAAJgBAAAAAAAARAEAAAAA
    AAAjAAAAAAAAAEoAAAAAAAAAzgAAAAAAAAAoAAAAAAAAAGUBAAAAAAAALgAAAAAAAAAEAAAAAAAA
    AOYAAAAAAAAAjgEAAAAAAAB0AAAAAAAAAN4BAAAAAAAA
- 0
- !!python/tuple
  - 400
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
train_on_keys:
- forces
- total_energy
train_val_split: random
two_body_latent_mlp_initialization: uniform
two_body_latent_mlp_latent_dimensions:
- 32
- 64
- 128
two_body_latent_mlp_nonlinearity: silu
type_names:
- Mo1L1
- S1L1
- S2L1
- W1L1
- Se1L2
- Se2L2
type_to_chemical_symbol: null
use_ema: true
val_idcs: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
    ZQpxAVgOAAAAOTQyMDAxMzgwMTk2MDBxAlgDAAAAY3B1cQNN9AFOdHEEUS6AAl1xAFgOAAAAOTQy
    MDAxMzgwMTk2MDBxAWEu9AEAAAAAAAAJAQAAAAAAAB4AAAAAAAAAFAEAAAAAAAAlAAAAAAAAAOwB
    AAAAAAAALgEAAAAAAACNAQAAAAAAAN8AAAAAAAAA5wAAAAAAAABkAAAAAAAAADEAAAAAAAAAogAA
    AAAAAABMAQAAAAAAAI8BAAAAAAAAAgAAAAAAAADHAQAAAAAAACsAAAAAAAAAvAEAAAAAAAB5AQAA
    AAAAAJkBAAAAAAAAxgEAAAAAAADwAAAAAAAAAEQAAAAAAAAANgEAAAAAAADqAAAAAAAAAEcAAAAA
    AAAARgEAAAAAAAA8AQAAAAAAABoAAAAAAAAAmQAAAAAAAAAbAAAAAAAAAMkAAAAAAAAA5QEAAAAA
    AAAPAAAAAAAAAO8BAAAAAAAAnwEAAAAAAADIAQAAAAAAANcBAAAAAAAA1QEAAAAAAAC8AAAAAAAA
    AAAAAAAAAAAA2gEAAAAAAAApAQAAAAAAAMEAAAAAAAAAnwAAAAAAAABmAAAAAAAAADMAAAAAAAAA
    kwAAAAAAAACwAAAAAAAAAIwBAAAAAAAAtgAAAAAAAAAAAQAAAAAAAEMBAAAAAAAAfQEAAAAAAACE
    AQAAAAAAAGMAAAAAAAAAOAAAAAAAAABXAQAAAAAAACYAAAAAAAAAvwAAAAAAAADCAQAAAAAAAOgB
    AAAAAAAAPQAAAAAAAAAnAAAAAAAAAMQAAAAAAAAAfwEAAAAAAABnAQAAAAAAACUBAAAAAAAA8gEA
    AAAAAACAAAAAAAAAAHkAAAAAAAAAeAAAAAAAAACXAQAAAAAAADoBAAAAAAAArAEAAAAAAAB3AQAA
    AAAAAJ4AAAAAAAAAugAAAAAAAABZAAAAAAAAAGkBAAAAAAAAJgEAAAAAAAAXAQAAAAAAAJEBAAAA
    AAAA0QEAAAAAAAAqAAAAAAAAAHUBAAAAAAAA8QAAAAAAAAA+AQAAAAAAAPoAAAAAAAAA7gAAAAAA
    AADaAAAAAAAAAHEAAAAAAAAA6gEAAAAAAACMAAAAAAAAAO4BAAAAAAAAHgEAAAAAAAA6AAAAAAAA
    ACcBAAAAAAAAGAEAAAAAAADAAAAAAAAAANQAAAAAAAAAvgAAAAAAAAD1AAAAAAAAADUBAAAAAAAA
    kAEAAAAAAADMAQAAAAAAAJYBAAAAAAAASQAAAAAAAADpAQAAAAAAACEAAAAAAAAAhQEAAAAAAACH
    AQAAAAAAAKsAAAAAAAAAsAEAAAAAAADzAQAAAAAAANkBAAAAAAAAIAEAAAAAAABHAQAAAAAAAHYB
    AAAAAAAAcgEAAAAAAAD8AAAAAAAAAGMBAAAAAAAAiQAAAAAAAABXAAAAAAAAAGEAAAAAAAAA8gAA
    AAAAAADtAAAAAAAAAMMBAAAAAAAAoAAAAAAAAAA3AQAAAAAAAHcAAAAAAAAACwAAAAAAAADOAQAA
    AAAAABYAAAAAAAAAGwEAAAAAAACJAQAAAAAAAAYBAAAAAAAAaAAAAAAAAAD7AAAAAAAAAC8AAAAA
    AAAA5gEAAAAAAAA/AQAAAAAAAO8AAAAAAAAArwEAAAAAAADkAAAAAAAAAJwAAAAAAAAAMQEAAAAA
    AADAAQAAAAAAAHYAAAAAAAAA1gAAAAAAAACNAAAAAAAAAGsBAAAAAAAA8wAAAAAAAAAHAQAAAAAA
    AGoAAAAAAAAAtQAAAAAAAACLAAAAAAAAANwAAAAAAAAAuwAAAAAAAADRAAAAAAAAAOIAAAAAAAAA
    OAEAAAAAAABfAAAAAAAAAF4AAAAAAAAAWwAAAAAAAADKAQAAAAAAAHABAAAAAAAAbAAAAAAAAACp
    AQAAAAAAAMoAAAAAAAAANgAAAAAAAAABAAAAAAAAAJEAAAAAAAAAcwEAAAAAAADLAQAAAAAAAEoB
    AAAAAAAAqgAAAAAAAABfAQAAAAAAADcAAAAAAAAAeAEAAAAAAACvAAAAAAAAABAAAAAAAAAAAgEA
    AAAAAAC7AQAAAAAAAMcAAAAAAAAAOQAAAAAAAACWAAAAAAAAAHoAAAAAAAAAhwAAAAAAAACmAQAA
    AAAAAA0BAAAAAAAA0wAAAAAAAACbAAAAAAAAANAAAAAAAAAApgAAAAAAAADMAAAAAAAAADsAAAAA
    AAAABQAAAAAAAADjAAAAAAAAAHsBAAAAAAAAsQEAAAAAAACCAAAAAAAAAIIBAAAAAAAA3QAAAAAA
    AAARAQAAAAAAAIgAAAAAAAAA/gAAAAAAAAAIAQAAAAAAAKkAAAAAAAAAQgAAAAAAAAD4AAAAAAAA
    AK4AAAAAAAAA6AAAAAAAAACuAQAAAAAAAOkAAAAAAAAAHwEAAAAAAACaAAAAAAAAAIMAAAAAAAAA
    vgEAAAAAAAAIAAAAAAAAAKUBAAAAAAAAEwAAAAAAAADFAQAAAAAAAFwBAAAAAAAAWwEAAAAAAAAh
    AQAAAAAAAC0AAAAAAAAAuQAAAAAAAABPAQAAAAAAACIAAAAAAAAAsgEAAAAAAAAoAQAAAAAAAJUB
    AAAAAAAAbgEAAAAAAAAZAQAAAAAAACkAAAAAAAAA/wAAAAAAAABnAAAAAAAAAKEBAAAAAAAA1AEA
    AAAAAACeAQAAAAAAAM8AAAAAAAAA4gEAAAAAAABwAAAAAAAAADIBAAAAAAAADwEAAAAAAABmAQAA
    AAAAABUAAAAAAAAAfQAAAAAAAADSAQAAAAAAAOUAAAAAAAAAPQEAAAAAAAA8AAAAAAAAAB0AAAAA
    AAAAqAAAAAAAAACgAQAAAAAAAB8AAAAAAAAAYAEAAAAAAAC4AQAAAAAAABIAAAAAAAAAQwAAAAAA
    AABUAAAAAAAAAG4AAAAAAAAAXgEAAAAAAABLAQAAAAAAACMBAAAAAAAAlAAAAAAAAACEAAAAAAAA
    AEIBAAAAAAAARQAAAAAAAABoAQAAAAAAAE0BAAAAAAAAlwAAAAAAAAC4AAAAAAAAABgAAAAAAAAA
    cwAAAAAAAACDAQAAAAAAAFAAAAAAAAAADAAAAAAAAABgAAAAAAAAAM0AAAAAAAAAWgEAAAAAAACA
    AQAAAAAAACsBAAAAAAAAEgEAAAAAAABpAAAAAAAAAEkBAAAAAAAA/QAAAAAAAADXAAAAAAAAADAA
    AAAAAAAAcgAAAAAAAADQAQAAAAAAAGUAAAAAAAAA3AEAAAAAAAA7AQAAAAAAAMIAAAAAAAAAhgAA
    AAAAAACaAQAAAAAAAGQBAAAAAAAAIAAAAAAAAAAyAAAAAAAAAOsAAAAAAAAAtAAAAAAAAADhAQAA
    AAAAAKEAAAAAAAAAWgAAAAAAAABOAQAAAAAAANsBAAAAAAAAqwEAAAAAAACOAAAAAAAAAKoBAAAA
    AAAApAEAAAAAAABvAAAAAAAAAIUAAAAAAAAA4AAAAAAAAAB7AAAAAAAAAEABAAAAAAAAfgEAAAAA
    AADWAQAAAAAAALcBAAAAAAAAKgEAAAAAAABTAQAAAAAAACQAAAAAAAAASAEAAAAAAAAvAQAAAAAA
    APkAAAAAAAAA2AAAAAAAAABiAAAAAAAAAMkBAAAAAAAAwQEAAAAAAABdAAAAAAAAAE4AAAAAAAAA
    xAEAAAAAAACKAAAAAAAAAH4AAAAAAAAAFQEAAAAAAACTAQAAAAAAAAMBAAAAAAAAvQEAAAAAAAAc
    AAAAAAAAAIoBAAAAAAAA1QAAAAAAAACcAQAAAAAAAIgBAAAAAAAAFAAAAAAAAADNAQAAAAAAAFYA
    AAAAAAAApwEAAAAAAAAtAQAAAAAAAJIAAAAAAAAAQAAAAAAAAAB1AAAAAAAAAOQBAAAAAAAALAAA
    AAAAAACGAQAAAAAAAKIBAAAAAAAAAwAAAAAAAADGAAAAAAAAAFQBAAAAAAAAuQEAAAAAAACVAAAA
    AAAAAE8AAAAAAAAADgAAAAAAAACLAQAAAAAAAJsBAAAAAAAAGQAAAAAAAAA5AQAAAAAAALMBAAAA
    AAAA3wEAAAAAAACYAAAAAAAAADUAAAAAAAAAdAEAAAAAAAA0AAAAAAAAAH8AAAAAAAAAPgAAAAAA
    AACxAAAAAAAAAAEBAAAAAAAAgQAAAAAAAACBAQAAAAAAALMAAAAAAAAADAEAAAAAAACtAAAAAAAA
    AMsAAAAAAAAA9gAAAAAAAAAJAAAAAAAAALUBAAAAAAAAUQEAAAAAAAAcAQAAAAAAAFgAAAAAAAAA
    awAAAAAAAACkAAAAAAAAAAsBAAAAAAAAfAAAAAAAAABYAQAAAAAAAHoBAAAAAAAAQQEAAAAAAAAs
    AQAAAAAAADABAAAAAAAAnQEAAAAAAABVAQAAAAAAAOcBAAAAAAAAyAAAAAAAAADFAAAAAAAAABcA
    AAAAAAAA9wAAAAAAAAC/AQAAAAAAAGEBAAAAAAAASAAAAAAAAABxAQAAAAAAAAoBAAAAAAAARQEA
    AAAAAABTAAAAAAAAAOEAAAAAAAAAtgEAAAAAAADgAQAAAAAAAN0BAAAAAAAAbAEAAAAAAAClAAAA
    AAAAAPEBAAAAAAAA7QEAAAAAAACdAAAAAAAAAKMBAAAAAAAAUAEAAAAAAAC9AAAAAAAAADQBAAAA
    AAAAMwEAAAAAAADTAQAAAAAAABYBAAAAAAAArAAAAAAAAADYAQAAAAAAAKMAAAAAAAAAPwAAAAAA
    AAAEAQAAAAAAAAoAAAAAAAAAjwAAAAAAAABVAAAAAAAAAJAAAAAAAAAAEQAAAAAAAABSAAAAAAAA
    AE0AAAAAAAAABgAAAAAAAACUAQAAAAAAAKgBAAAAAAAAEAEAAAAAAAANAAAAAAAAAOsBAAAAAAAA
    VgEAAAAAAACyAAAAAAAAAHwBAAAAAAAARgAAAAAAAABRAAAAAAAAANsAAAAAAAAAwwAAAAAAAADw
    AQAAAAAAACQBAAAAAAAA3gAAAAAAAADSAAAAAAAAAG0BAAAAAAAAHQEAAAAAAAAFAQAAAAAAAK0B
    AAAAAAAAXQEAAAAAAAAiAQAAAAAAAFIBAAAAAAAAEwEAAAAAAADPAQAAAAAAALoBAAAAAAAA4wEA
    AAAAAAAaAQAAAAAAAG0AAAAAAAAAagEAAAAAAABLAAAAAAAAAKcAAAAAAAAA7AAAAAAAAABiAQAA
    AAAAAEEAAAAAAAAABwAAAAAAAABZAQAAAAAAAFwAAAAAAAAAtAEAAAAAAAAOAQAAAAAAAJIBAAAA
    AAAAbwEAAAAAAAC3AAAAAAAAAPQAAAAAAAAA2QAAAAAAAABMAAAAAAAAAJgBAAAAAAAARAEAAAAA
    AAAjAAAAAAAAAEoAAAAAAAAAzgAAAAAAAAAoAAAAAAAAAGUBAAAAAAAALgAAAAAAAAAEAAAAAAAA
    AOYAAAAAAAAAjgEAAAAAAAB0AAAAAAAAAN4BAAAAAAAA
- 400
- !!python/tuple
  - 100
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
validation_batch_size: 5
var_num_neighbors: 2.963959217071533
verbose: info
wandb: true
wandb_project: WSe2_twistml
warn_unused: false
